server:
  port: 8081

spring:
  application:
    name: configservice
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Raulcudris/microservices-fargate-demo.git
          default-label: main
          search-paths: config-data
