server:
  port: 8081

spring:
  application:
    name: configservice
  cloud:
    config:
      server:
        git:
          uri: https://github.com/loochon/config-data.git
          default-label: main
          search-paths: config-data
          username: ${GIT_NAME}
          password: ${GIT_TOKEN2}
